In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.0


In [6]:
#Creating Array
Data=np.array([1,2,3,4])
print(Data)

[1 2 3 4]


In [7]:
type(Data)

numpy.ndarray

In [14]:
#Two Dimension
List1=[1,2,3,5]
List2=[1,5,56,5]
arr=np.array([List1,List2])
print(arr)

[[ 1  2  3  5]
 [ 1  5 56  5]]


In [15]:
#Dimensional
print(arr.ndim)

2


In [16]:
print(Data.ndim)

1


In [18]:
#Numpy Array Attribut
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [20]:
print("Shape",arr1.shape)
print("Size",arr1.size)
print("dtype",arr1.dtype)
print("N-Dimension",arr1.ndim)

Shape (2, 3)
Size 6
dtype int64
N-Dimension 2


In [24]:
# Array intialization Array
zero_arr=np.zeros((2,3)) #shape parameter pass
print(zero_arr)

ones_arr=np.ones((2,1))
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]]


In [25]:
#full Array
full_arr=np.full((3,2),7)  #two parameter pass 1 is shape of array and 2 is element
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [29]:
# identity Matrix
id_arr=np.eye(3) #Always # Square Matrix Digonal ELement Ones
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#empty Array
print(np.empty(2)) #it generate two random value

[1. 1.]


In [35]:
# Evenly space Array
print(np.arange(1,10,2)) # it is run n-1


[1 3 5 7 9]


In [37]:
#specific number of equally spaced value  between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [38]:
# Random Value Array
rand_arr=np.random.rand(3,2)  #it give float values and pass shape as argument
print(rand_arr)

[[5.88890146e-01 6.63124067e-01]
 [1.96795055e-01 7.07130946e-04]
 [3.55587891e-01 8.27285791e-01]]


In [43]:
#Random value In Integer
rand_int=np.random.randint(1,10,(3,3)) #3 argument pass stating and ending 10 then shape
print(rand_int)

[[5 1 1]
 [8 3 1]
 [6 8 4]]


In [51]:
#Array Indexing and Slicing
a=np.array([1,2,3,5]) #index start from 0 and end length-1
print(a)

[1 2 3 5]


In [52]:
#indexing
print(a[0])
print(a[3])
print(a[-1]) # 4-1=> index 3

1
5
5


In [55]:
#slicing 
#array[start:stop:step
#stop index, that is not include in uotput
print(a[0:3]) #first three element
print(a[-3:]) #last three element
print(a[1:4]) #middle three
print(a[0:4:2]) # jump by 2
print(a[0::2])

[1 2 3]
[2 3 5]
[2 3 5]
[1 3]
[1 3]


In [56]:
#Two Dimensional Array
arr2=np.array([[1,3,4,3,4],[3,4,6,36,4]])
print(arr2)

[[ 1  3  4  3  4]
 [ 3  4  6 36  4]]


In [61]:
#indexing
print(arr2[0]) #first row
print(arr2[1]) #second row
print(arr2[0][0]) #first element row first column first
print(arr2[0][1]) # first row and second colum element
print(arr2[1][0]) #second row and first cloumn element

[1 3 4 3 4]
[ 3  4  6 36  4]
1
3
3


In [63]:
#silcing
print(arr2[1])
print(arr2[1:])

[ 3  4  6 36  4]
[[ 3  4  6 36  4]]


In [68]:
print(arr2[:,1]) #it give fisrt column
print(arr2[:,2])


[3 4]
[4 6]


In [72]:
# Array Reshaping And flattong
arr3=np.array([1,2,3,4])
print(arr3)
reshape=arr3.reshape((4,1)) #row and column give as argument
print(reshape)
reshape1=arr3.reshape((2,2))
print(reshape1)



[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]


In [73]:
print(reshape1.flatten())

[1 2 3 4]


In [80]:
#array stacking and spliting
a1=np.array([1,2,3,4])
b=np.array([14,6,7,3])
print(np.vstack(a1))
print(np.hstack(b))
print(np.vstack((a1,b))) #vertial row wise 1 dimension and 1 dimesion become two dimesion
print(np.hstack((a1,b))) #horizonatal column wise


[[1]
 [2]
 [3]
 [4]]
[14  6  7  3]
[[ 1  2  3  4]
 [14  6  7  3]]
[ 1  2  3  4 14  6  7  3]


In [87]:
#spliting
c=np.array([[1,2,3,4],[3,4,3,5]])
h_split=np.hsplit(c,4)
for s in h_split:
    print(s)

c=np.array([[1,2,3,4],[3,4,3,5]])
v_split=np.vsplit(c,2)
for s in v_split:
    print(s)

[[1]
 [3]]
[[2]
 [4]]
[[3]
 [3]]
[[4]
 [5]]
[[1 2 3 4]]
[[3 4 3 5]]


In [91]:
#Mathematical Operation
a=np.array([12,3,-30,70,302])
print(a+30)
print(a*2)
print(a/2)
print(a%2)
print(a-30)
print(np.square(a))
print(np.sqrt(a))
print(np.sin(a))

[ 42  33   0 100 332]
[ 24   6 -60 140 604]
[  6.    1.5 -15.   35.  151. ]
[0 1 0 0 0]
[-18 -27 -60  40 272]
[  144     9   900  4900 91204]
[ 3.46410162  1.73205081         nan  8.36660027 17.3781472 ]
[-0.53657292  0.14112001  0.98803162  0.77389068  0.39595283]


C:\Users\noore elahi\AppData\Local\Temp\ipykernel_3544\1048556842.py:9: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a))


In [94]:
a=np.array([1,2,3,4,5])
b=np.array([2,4,6,7,4])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
#transpose .T

[ 3  6  9 11  9]
[-1 -2 -3 -3  1]
[ 2  8 18 28 20]


In [96]:
#Dot product
print(np.dot(a,b)) #fisrt multipy with corresponding elemt and last add the total value

76


In [99]:
#Statistical Function
a=np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))

15
3.0
3.0
1.4142135623730951
5
1


In [103]:
# Array Comparison
a=np.array([1,2,3,4,5])
b=np.array([2,2,6,7,4])
print(a==b) #compare elemnt of each arrqay
print(np.array_equal(a,b)) #compare array complete


[False  True False False False]
False
[False False False False  True]


In [105]:
# Brodcasting
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([2,4,6,7,4])
print(a+b)

[[ 3  6  9 11  9]
 [ 3  6  9 11  9]]


In [107]:
#Error handling
data1=np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [108]:
print(np.isnan(data1))

[False False  True False False]


In [109]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [111]:
#Save and load array
a=np.array([1,2,3,4,5])
print(a)
np.save('my.npy',a)

[1 2 3 4 5]


In [112]:
#load array
a=np.array([1,2,3,4,5])
d=np.load('my.npy')
print(d)

[1 2 3 4 5]
